### ISSUE TITLE
Checked state of Radiobox not visibile

### ISSUE THREAD

**Issue by jonkoops** [Amsterdam/amsterdam-styled-components#1165]
**Describe the bug**
When using the Radio in Internet Explorer the checked state is not visible.

**To Reproduce**
1. Open the Radio story in Internet Explorer

**Expected behavior**
The checked state is clearly visible.

**Screenshots**
![Error in IE](https://user-images.githubusercontent.com/695720/93438108-23c02300-f8cd-11ea-84ad-09b21a6c511b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet Explorer
 - Version: 11

**Comment by robinpiets** [comment]
Thanks for alerting this! I'm making a PR

**Comment by robinpiets** [comment]
Fixed #1166
