### ISSUE TITLE
Search button in header is elongated

### ISSUE THREAD

**Issue by jonkoops** [Amsterdam/amsterdam-styled-components#1227]
**Describe the bug**
The search button in the header is elongated and should be square as per design.

**To Reproduce**
1. Go to data.amsterdam.nl/
2. Check the search bar

**Expected behavior**
The button is sqaure.

**Screenshots**
Actual
![image](https://user-images.githubusercontent.com/695720/95449804-8b660d00-0965-11eb-8ccb-7e7df5c83e0c.png)

Expected
![image](https://user-images.githubusercontent.com/695720/95449840-9e78dd00-0965-11eb-8fa0-9bf1b51beb4c.png)

**Comment by robinpiets** [comment]
That's because all primary / secondary buttons have a min-width. You should use the "Button with only an Icon" and give it a custom background color:

https://amsterdam.github.io/amsterdam-styled-components/iframe.html?id=ui-form-button--default-primary-variant&viewMode=docs#with-only-an-icon

**Comment by robinpiets** [comment]
Or custom overwrite the min-width with 'inherit'

@chrisvanmook you did that for another component as well, right?
