### ISSUE TITLE
`SearchBar` component should be wrapped in `<form>` element and should return event on submit

### ISSUE THREAD

**Issue by janjaap** [Amsterdam/amsterdam-styled-components#133]
Since the `SearchBar` component is a stand-alone component and that it has a submit button, the input and button elements should come wrapped in a `<form>` element to prevent submitting another form on a page when a user hits return or clicks the submit button.

Also, the `onSubmit` handler returns the actual value of the field and not the event object itself. This makes it impossible to call `preventDefault`, amongst other use cases for the event object.

**Comment by chrisvanmook** [comment]
@janjaap checkout https://github.com/Amsterdam/amsterdam-styled-components/releases/tag/v0.19.0
`onSubmit` is deprecated here. That means you should wrap the SearchBar component inside a <form> yourself :)
