### ISSUE TITLE
Searchbar Issue when typing inside of the input field when using SearchBar component inside of Modal component

### ISSUE THREAD

**Issue by Jorisslagter** [Amsterdam/amsterdam-styled-components#1485]
**Describe the bug**
When a SearchBar component is used inside of a Modal component, the SearchBar input field loses focus after a key is pressed. It looks like this is occurring when there is some kind of state associated and/or when it triggers a render update on the parent component (in this case the Modal).

**To Reproduce**

1. Go the to code example and type in the search bar and you will lose your focus.
2. Toggle the state logic (remove the onChange logic) that causes a rerender on the modal component. And you can see the issue isn't there anymore. 

**Expected behavior**
I want the search input to stay in focus when I am typing in a search string

**Live Code example**
https://codesandbox.io/s/eloquent-dream-8bo2p?file=/src/App.tsx

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows and Mac
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  87.0.4280.141

**Comment by jonkoops** [comment]
@Jorisslagter did you manage to get a fix in the works for this one? Otherwise I will add it to our backlog.
