### ISSUE TITLE
Map component doesnt show feedback when focussed

### ISSUE THREAD

**Issue by frankfe-amsterdam** [Amsterdam/amsterdam-styled-components#1597]
**Description**
When I focus on the map, the element with data-testid="map" gets outline="none" so the user gets no feedback on the focussed element.

**To Reproduce**
1. Go to 'https://id.amsterdam.nl/overlast-melden'
2. Tab until the Map gets focus
3. See that it sets outline to none when focussed

**Expected behavior**
Outline should be displayed so the user gets feedback

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 90.0.4430.85

**Comment by jonkoops** [comment]
Hi Frank, unless I am mistaken somehow I believe the `Map` component you are talking about is from our [React Maps](https://github.com/amsterdam/react-maps) library. If this is the case could you report your issue there?

Feel free to open up a PR to fix this issue! :+1:

**Comment by frankfe-amsterdam** [comment]
You are right. 👍 

I moved it over.

**Comment by jonkoops** [comment]
Awesome, closing this issue.
