### ISSUE TITLE
Add type validation for `fromTheme` function

### ISSUE THREAD

**Issue by janjaap** [Amsterdam/amsterdam-styled-components#16]
The `fromTheme` function takes in a string where the props are separated by dots `.`. To improve DX, we should add type validation for the parameter(s) that determine(s) the value from the theme configuration prop.

**Comment by jonkoops** [comment]
As far as I know it's not possible to create type safe strings with seperators. @janjaap Do you have some example code of how it works now and how you expect it to work?

**Comment by janjaap** [comment]
Not sure this issue is still valid.

**Comment by jonkoops** [comment]
Ok, then I will close this issue. Feel free to re-open if it's still relevant.
