### ISSUE TITLE
Margins of the `HeaderNavigation` no longer match the four point grid

### ISSUE THREAD

**Issue by royderks** [Amsterdam/amsterdam-styled-components#165]
The Amsterdam Design System is moving towards a four point grid, the `GridContainer` is also using this four point grid. Therefore the inner margins of the `HeaderNavigation` component must be changed.  

For this the values for `margin-left` and `margin-right` must become `29px`, so the total will be `44px` which is the same as the left and right margins of the `GridContainer`

**Comment by jonkoops** [comment]
Relates to #197. @royderks has this been fixed in the PR that has been merged?
