### ISSUE TITLE
globalStyle cannot be overridden

### ISSUE THREAD

**Issue by aditudorache** [Amsterdam/amsterdam-styled-components#176]
**Describe the bug**
Changes in the globalStyle parameter of the theme does not override the default global style

**To Reproduce**
```javascript
const themeOverrides = {
  globalStyle: `
  * {
    box-sizing: content-box;
  }

  body {
    font-family: Arial;
  }
`,
};

const App = () => {
  return (
    <ThemeProvider overrides={themeOverrides}>
      <GlobalStyle />
      <Heading>Test</Heading>
    </ThemeProvider>
}
```

**Expected behavior**
- The font of the heading should be Arial
- The box-sizing should be content-box

**Comment by chrisvanmook** [comment]
@aditudorache themeOverrides should be an object like the `ascDefaultTheme`, so let's say you want to override the color: 
const themeOverrides = {
  color: {
   primary: {
    main: 'red',
    dark: 'purple',
  },
  }
};

const App = () => {
  return (
    <ThemeProvider overrides={themeOverrides}>
      <GlobalStyle />
      <Heading>Test</Heading>
    </ThemeProvider>
}
