### ISSUE TITLE
None of the basic form element can be references by `ref`

### ISSUE THREAD

**Issue by janjaap** [Amsterdam/amsterdam-styled-components#218]
**Describe the bug**

For any form elements (radiobutton, checkbox, ...) it can be very handy, or at times even a requirement, to have a reference to an element. This is currently not possible with the components that are exposed in this lib.

**To Reproduce**
1. Create a component:
    ```jsx
    import React, { useRef } from 'react';
    import { Checkbox } from '@datapunt/asc-ui';
    
    export const Form = () => {
      const cbRef = useRef(null);
    
      return (
        <form>
          <Checkbox ref={cbRef} />
        </form>
      );
    };
    ```
2. Observe the following error in the dev console:
    > Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

**Expected behaviour**
No errors/warnings in the console

**Comment by royderks** [comment]
Is this resolved by this merge @janjaap? https://github.com/Amsterdam/amsterdam-styled-components/pull/205

**Comment by janjaap** [comment]
No, the `Checkbox` component (or any form component for that matter) needs to be exported with `React.forwardRef()`

**Comment by jonkoops** [comment]
@janjaap Could you open up a PR to add this functionality to the form components? Any help would be appreciated.

**Comment by janjaap** [comment]
@jonkoops Would love to, but my TypeScript knowledge doesn't go far enough to solve this. I'm relying on the package maintainers here.

**Comment by royderks** [comment]
@janjaap `type: any`? We can help completing the types for you

**Comment by jonkoops** [comment]
If there is nobody that can pick this up I can go ahead and add this functionality. Marked this as a good first contribution if anyone is interested.

**Comment by royderks** [comment]
@jasperswart wants to pick this issue

**Comment by jonkoops** [comment]
#256 will implement this for the `Checkbox` component, after this we will have to add the other components and write the appropriate documentation.

**Comment by jonkoops** [comment]
Merged this feature for the `Select` component as well.

**Comment by jonkoops** [comment]
#284 will implement the `Radio` component.

**Comment by jonkoops** [comment]
#294 will implement this for the `Input` component

**Comment by jonkoops** [comment]
We still need to implement this for the `Button` component and then we're all done. Some documentation should also be added.
