### ISSUE TITLE
We want to white label the Signalen App of Amsterdam

### ISSUE THREAD

**Issue by spreeker** [Amsterdam/amsterdam-styled-components#223]
I'd like to add logo's of different gemeente on the signalen app which is now impossible. Signalen is styled with the amsterdam-styled-components.

What is the best way to migrate away from an Amsterdam specific style to a more configurable white label version in a way we are still able to collaborate to on the fronted code of signalen.

**Comment by jonkoops** [comment]
@spreeker Is the intention to re-brand your app for different municipalities or variations of the municipality of Amsterdam?

**Comment by jonkoops** [comment]
@spreeker Is this issue still relevant?

**Comment by jonkoops** [comment]
Closing this issue due to unresponsiveness. Feel free to leave a comment in case this needs to be re-opened.
