### ISSUE TITLE
Chevron in 'Card' is deprecated in DS

### ISSUE THREAD

**Issue by RCNEW** [Amsterdam/amsterdam-styled-components#285]
The atoms "card default with action" shows a chevron (>) on the bottom here:
https://amsterdam.github.io/amsterdam-styled-components/?path=/story/atoms-card--default-with-action

![image](https://user-images.githubusercontent.com/781377/75547463-36efcc00-5a2b-11ea-8efb-441dea6b5b00.png)

But this chevron in is deprecated in DS here on June 11 2019: https://designsystem.amsterdam.nl/7awj1hc9f/p/46e2d8-toptask-button

I don't see this chevron used anywere (anymore?) in this way on data.amsterdam.nl.
So I suggest this chevron to be removed from 'card default with action' and all related atoms in a future release.

**Comment by jonkoops** [comment]
Yeah, this should be removed from the component indeed.

**Comment by jasperswart** [comment]
I will do this one

**Comment by jonkoops** [comment]
Great, thanks for picking it up @jasperswart

**Comment by jonkoops** [comment]
After some discussion we have come to the conclusion that we're currently abusing the Card component as a 'TopTask' button. This means that we will have to consider the Card component to be outside of the design system.

This means the following:
- We need to align on what the 'Card' component is in the design system, either deprecating the component or formalizing it in the design system.
- We need to decide if we should implement a new 'TopTask' button in Amsterdam Styled Components

I'll make sure that we have the appropriate issues for this together with Chris. For now we're going to consider this issue as blocked until the aforementioned action items are resolved.

**Comment by jonkoops** [comment]
@RCNEW I've created issue #295 which will implement this functionality. I am closing this issue for administrative purposes.
