### ISSUE TITLE
Textarea component

### ISSUE THREAD

**Issue by Jeffrey-Zutt** [Amsterdam/amsterdam-styled-components#480]
Hi all,

We'd like to use the `Textarea` - component, as described in the designsystem, in our application.
https://designsystem.amsterdam.nl/7awj1hc9f/p/939dd9-text-area

Is that something that is feasible?

Thank you!

**Comment by jonkoops** [comment]
@Jeffrey-Zutt We certainly want to have this component. If you have any time available feel free to pick it up.

**Comment by Jeffrey-Zutt** [comment]
@jonkoops 
I created a pull request:
https://github.com/Amsterdam/amsterdam-styled-components/pull/491

**Comment by jonkoops** [comment]
Nice, thanks @Jeffrey-Zutt. I'll see if we can get some people to take a look at it!
