### ISSUE TITLE
Unable to set Icon color

### ISSUE THREAD

**Issue by alimpens** [Amsterdam/amsterdam-styled-components#543]
**Describe the bug**
The Icon component has a 'color'-prop for setting the icon color. This prop expects a string. When setting this prop to one of the strings in Theme.Colortype or a hex code, the color doesn't change. 

**To Reproduce**
1. Import an Icon
2. Set the 'color' prop
3. See that the color doesn't change

**Expected behavior**
I expect the color to change. It seems the prop is expecting a string from Theme.Colortype, but these aren't colors, just categories. I think it would be more intuitive if you could just set a (hex) color directly on the Icon component.

**Comment by jasperswart** [comment]
the color can only be one of the following:

<div>
    <Icon size={40} color="primary">
      <Location />
    </Icon>
    Primary
  </div>
  <div style={{ paddingTop: 20 }}>
    <Icon size={40} color="secondary">
      <Location />
    </Icon>
    Secondary
  </div>
  <div style={{ paddingTop: 20 }}>
    <Icon size={40} color="tint">
      <Location />
    </Icon>
    Tint
  </div>
  <div style={{ paddingTop: 20 }}>
    <Icon size={40} color="none">
      <Location />
    </Icon>
    None
  </div>
  <div style={{ paddingTop: 20 }}>
    <Icon size={40} color="support">
      <Location />
    </Icon>
    support
  </div>
  <div style={{ paddingTop: 20 }}>
    <Icon size={40} color="error">
      <Location />
    </Icon>
    error
  </div>
  <div style={{ paddingTop: 20 }}>
    <Icon size={40} color="default">
      <Location />
    </Icon>
    default
  </div>


this is new documentation:
https://amsterdam.github.io/amsterdam-styled-components/?path=/docs/experimental-atoms-icon--colors

**Comment by alimpens** [comment]
I got the colors working with a fresh install, but it still doesn't seem very intuitive. Only 'primary', 'secondary' and 'error' actually change the color, the rest don't change it. In the default theme the ColorTypes 'primary', 'secondary' etc actually have multiple colors associated with them, how would you know which color to expect?

If icons are only supposed to be one of the theme colors, you would need to be able to select one of the colors in the palette associated with the ColorType, right?

(One more thing: when you set the color prop of an Icon, it adds a prop to the containing span in the DOM. This seems a bit unnecessary. Is that on purpose?)

**Comment by jonkoops** [comment]
@alimpens Yeah, totally, I think it would make sense if the color prop is always a color code. In this case perhaps we could also use the `themeColor` util to make this more sensible. For example:

```tsx
<Icon color={themeColor('primary', 'tint-1')}></Icon>
<Icon color="#ff00ff"></Icon>
<Icon color="rgba(255, 0, 255, 0.75)"></Icon>
```

@chrisvanmook @royderks What do you think abou this?

> (One more thing: when you set the color prop of an Icon, it adds a prop to the containing span in the DOM. This seems a bit unnecessary. Is that on purpose?)

This is a bug, it has to do with how `as` or `forwardedAs` is used in some cases.

**Comment by jasperswart** [comment]
I am picking up this one
