### ISSUE TITLE
ErrorMessage is in DOM if it has no `message` prop

### ISSUE THREAD

**Issue by robinpiets** [Amsterdam/amsterdam-styled-components#545]
### The ErrorMessage should not be 'visible' if the `message` prop is not set

---

![image](https://user-images.githubusercontent.com/7781865/81291950-0cde0a00-906b-11ea-82a8-7dd04d698a65.png)

---

![image](https://user-images.githubusercontent.com/7781865/81292019-28e1ab80-906b-11ea-9683-ebf9dcabcd57.png)

**Comment by jonkoops** [comment]
I think that the alert should be rendered conditionally in the first place, it seems to me that user is responsible for hiding an element if it is not intended to be shown.

```tsx
{errors.required && (
  <ErrorMessage message="This field is required." />
)}
```

**Comment by robinpiets** [comment]
Hmm.. I don't think that's nice. I use this element like this:
```
<ErrorMessage message={errorMessage} />
```

Why should I make this?
```
{errorMessage && <ErrorMessage message={errorMessage} />
```

It would be better not to render the whole component if no message prop is provided.

What do you think @jasperswart @chrisvanmook ?

**Comment by jonkoops** [comment]
Yeah, it might look convenient but I find the line a bit arbitrary. What if we add other props that might influence the contents of this component, or for other components where do we draw the line?

I like the fact that the code is explicit, and in line with how other elements of React work. HTML elements work the same, if you render an empty div the div will still be there which is nice and predictable.

**Comment by robinpiets** [comment]
Okay, good point. 👍  Closing this issue.
