### ISSUE TITLE
Refactor svgFill to pass a custom color

### ISSUE THREAD

**Issue by chrisvanmook** [Amsterdam/amsterdam-styled-components#576]
The `svgFill` method should be refactored to accept a color code only. Also note that the color prop for the `Icon` component will have to start using this method.

See discussion in #574

**Comment by jasperswart** [comment]
I will pick this up

**Comment by robinpiets** [comment]
Maybe we can also change this in the Paragraph component? It has a similar issue.

**Comment by jonkoops** [comment]
@robinpiets Could you give an example?

**Comment by robinpiets** [comment]
Now Paragraph uses TypographyStyle, and `color` is defined like this:
```
${({ color }) =>
    color &&
    css`
      color: ${themeColor(color)};
    `}
```

We can change this to pass a string, so we can use it like this:
`<Paragraph color={themeColor("tint", "level3")}>...`
or
`<Paragraph color="#bbb">...`

**Comment by jonkoops** [comment]
Makes sense, I'd like to see that as well. Although I wonder why this prop exists in the first place since it's just a text element. Should we remove it instead?

**Comment by robinpiets** [comment]
Yeah, it's a strange prop. Shall I make a new PR to change it into this:
```
${({ color }) =>
  color &&
  css`
      color: ${color};
  `}
```

**Comment by jonkoops** [comment]
Sounds good, but let's deprecate the property at the same time. People should just style it in the color they need using `styled(Paragraph)`.

**Comment by robinpiets** [comment]
I will fix the Paragraph color prop in a separate PR
